const PATHS = {
    CLEAR: '/clear',
    ORDER_DETAIL: '/order/detail',
    ORDER_LISTALL: '/order/listall',
    ORDER_EDITSTATUS: '/order/editStatus',
    ORDER_EDITDEADLINE: '/order/editDeadline',
    ORDER_EDITMATERIALAMOUNT: '/order/editMaterialAmount',
    ORDER_EDITCLIENT: '/order/editClient',
    ORDER_EDITPRODUCTAMOUNT: '/order/editProductAmount',
    ORDER_EDITSTARTDATE: '/order/editStartDate',
    ORDER_CREATE: '/order/create',
    ORDER_EDITDESCRIPTION: '/order/editDescription',
    ORDER_CHECKSTATUS: '/order/checkStatus',
    ORDERS_TIMESTAMP: '/orders/timeStamp',

    PRODUCT_ALLTYPE: '/product/allType',
    PRODUCT_LISTALL: '/product/listall',
    PRODUCT_DETAIL: '/product/detail',
    PRODUCT_EDITNAME: '/product/editName',
    PRODUCT_EDITUNIT: '/product/editUnit',
    PRODUCT_EDITUNITPRICE: '/product/editUnitPrice',
    PRODUCT_EDITREMAINING: '/product/editRemaining',
    PRODUCT_EDITMATERIALAMOUNT: '/product/editMaterialAmount',
    PRODUCT_EDITDESCRIPTION: '/product/editDescription',
    PRODUCT_CREATE: '/product/create',

    STORE_LISTALL: '/store/listall',
    STORE_ALLTYPE: '/store/allType',
    STORE_ADD: '/store/add',
    STORE_ADDTYPE: '/store/addType',
    STORE_TIMESTAMP: '/store/timeStamp',

    USER_LISTALL : '/user/listall',
    USER_REGISTER : '/user/register',
    USER_SENDCODE: '/user/sendCode',
    USER_PERMISSION_MODIFY: '/user/permission/modify',
    USER_RETRIEVEPASSWORD: '/user/retrievePassword',
    USER_EDITPASSWORD: '/user/editPassword',
    USER_GETEMAIL: '/user/getEmail',
    USER_LOGOUT: '/user/logout',
}
export default PATHS;